### PR TITLE
Merge pull request #1 from sorengranfeldt/master

### PR DESCRIPTION
**Pull request by johnekare-advania**
Latest changes from Granfeldt

### CODE REVIEW

**Comment by johnekare-advania** [comment]
Merging experimentation Branch to Master after pulling latest changes from Granfeldt.

**Comment by sorengranfeldt** [comment]
What is this about?

**Comment by johnekare-advania** [comment]
> What is this about?

I am utterly embarred and sorry. I didn't have my browser tabs in order. I meant to merge your last changes with my forked version. Not the other way around. Apologies!

**Comment by sorengranfeldt** [comment]
No worries :-) I'll close this PR.

**Comment by johnekare-advania** [comment]
Thank you! :)

**Pull request closed without merging**
